# List of cops can be found here:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml
# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  ExtraDetails: true
  TargetRubyVersion: 2.5

# readability is Actually Good
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Lint/Void:
  Exclude:
    - app/models/jupiter_core/locked_ldp_object.rb

# A calculated magnitude based on number of assignments,
# branches, and conditions.
Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 1000 # default 100

# A complexity metric that is strongly correlated to the number
# of test cases needed to validate a method.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120 # default is 80
  IgnoredPatterns: ['\A\s*#'] # tweak to ignore long comments, which often are examples or URLs that are not easily broken up

# Avoid methods longer than 10 lines of code.
Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 500 # default 100

# A complexity metric geared towards measuring complexity for a human reader.
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - app/models/jupiter_core/search.rb
    - app/models/jupiter_core/locked_ldp_object.rb
    - app/models/jupiter_core/deferred_faceted_solr_query.rb


Naming/PredicateName:
  Exclude:
    - app/models/jupiter_core/locked_ldp_object.rb
Naming/AccessorMethodName:
  Exclude:
    - app/models/concerns/item_properties.rb

Naming/FileName:
  Exclude:
    - Dangerfile
    - Rakefile
    - Gemfile

# TODO: Review and fix these
Naming/MemoizedInstanceVariableName:
  Exclude:
    - app/models/jupiter_core/deferred_faceted_solr_query.rb
    - app/models/concerns/item_properties.rb

# TODO: Review and fix these
Naming/UncommunicativeMethodParamName:
  Exclude:
    - app/models/jupiter_core/locked_ldp_object.rb
    - app/models/jupiter_core/deferred_faceted_solr_query.rb
    - app/models/jupiter_core/search.rb
    - app/services/statistics.rb

# We using activefedora here... not activerecord
Performance/UnneededSort:
  Exclude:
    - app/models/jupiter_core/locked_ldp_object.rb

Rails:
  Enabled: true

# Autocorrecting this actively breaks code
Rails/FindEach:
  Enabled: false

# TODO: False postivies on headers, remove this once on rubocop > 0.56.0 as fixed in next release
Rails/HttpPositionalArguments:
  Exclude:
    - test/controllers/file_sets_controller_test.rb

# There comes a point where I question Rubocop's maintainer's sanity
Rails/UnknownEnv:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

# indentation is an endangered resource
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/ClassVars:
  Exclude:
    - !ruby/regexp /_test\.rb$/

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# Checks if there is a magic comment to enforce string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/RedundantBegin:
  Exclude:
    - bin/yarn

Style/RedundantSelf:
  Exclude:
    - app/models/jupiter_core/locked_ldp_object.rb

# Perfer to use // but %r can be better in certain scenarios
Style/RegexpLiteral:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/TrivialAccessors:
  Exclude:
    - app/models/jupiter_core/locked_ldp_object.rb

# Use %w or %W for arrays of words.
Style/WordArray:
  Enabled: false

Performance/TimesMap:
  Enabled: false
