---
# Note: order is roughly based on probability of usage
language:
  - code: eng
    uri: http://id.loc.gov/vocabulary/iso639-2/eng
  - code: fre
    uri: http://id.loc.gov/vocabulary/iso639-2/fre
  - code: other
    uri: http://terms.library.ualberta.ca/other
  - code: ukr
    uri: http://id.loc.gov/vocabulary/iso639-2/ukr
  - code: ger
    uri: http://id.loc.gov/vocabulary/iso639-2/ger
  - code: jpn
    uri: http://id.loc.gov/vocabulary/iso639-2/jpn
  - code: ita
    uri: http://id.loc.gov/vocabulary/iso639-2/ita
  - code: rus
    uri: http://id.loc.gov/vocabulary/iso639-2/rus
  - code: zxx
    uri: http://id.loc.gov/vocabulary/iso639-2/zxx
  - code: zho
    uri: http://id.loc.gov/vocabulary/iso639-2/zho
  - code: spa
    uri: http://id.loc.gov/vocabulary/iso639-2/spa
