old_license:
  attribution_3_0_international: http://creativecommons.org/licenses/by/3.0/
  attribution_noncommercial_3_0_international: http://creativecommons.org/licenses/by-nc/3.0/
  attribution_sharealike_3_0_international: http://creativecommons.org/licenses/by-sa/3.0/
  attribution_noncommercial_noderivatives_3_0_international: http://creativecommons.org/licenses/by-nc-nd/3.0/
  attribution_noncommercial_sharealike_2_5_canada: http://creativecommons.org/licenses/by-nc-sa/2.5/ca/
