---
publication_status:
  - code: published
    uri: http://purl.org/ontology/bibo/status#published
  - code: draft
    uri: http://purl.org/ontology/bibo/status#draft
  - code: submitted
    uri: http://vivoweb.org/ontology/core#submitted
