subject:
  "Edmonton Folk Music Festival": http://viaf.org/viaf/148861489
  "Folk music festivals": http://id.loc.gov/authorities/subjects/sh2008004058
  "Edmonton (Alta.)": http://id.loc.gov/authorities/names/n79007225
