# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  saml_assertion_consumer_service_url: <%= ENV['SAML_ASSERTION_CONSUMER_SERVICE_URL'] %>
  saml_issuer: <%= ENV['SAML_ISSUER'] %>
  saml_private_key: <%= ENV['SAML_PRIVATE_KEY'] %>
  saml_certificate: <%= ENV['SAML_CERTIFICATE'] %>
  saml_idp_cert: <%= ENV['SAML_IDP_CERT'] %>
  saml_idp_sso_target_url: <%= ENV['SAML_IDP_SSO_TARGET_URL'] %>

  database_url: <%= ENV['DATABASE_URL'] %>
  fcrepo_url: <%= ENV['FCREPO_URL'] %>
  fcrepo_user: <%= ENV['FCREPO_USER'] %>
  fcrepo_password: <%= ENV['FCREPO_PASSWORD'] %>
  fcrepo_basepath: <%= ENV['FEDORA_BASEPATH'] %>

  solr_url: <%= ENV['SOLR_URL'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  
  sidekiq_pidfile: tmp/pids/sidekiq.pid
  sidekiq_logfile: <%= ENV['sidekiq_logfile'] %>
  
development: *default
  secret_key_base: c0a4bf2c5890d0fa86e1459dd189bc4c5a02f412067b610490885c8c312bf0cea5d988e075761ba7277a8291041c1b2e7cf6c373d4d6f43d4522bc48db76cc1a

  saml_assertion_consumer_service_url: ''
  saml_issuer: ''
  saml_private_key: ''
  saml_certificate: ''
  saml_idp_cert: ''
  saml_idp_sso_target_url: ''
  
  fcrepo_url: <%= ENV['FCREPO_URL'] || 'http://localhost:8080/fcrepo/rest' %>
  fcrepo_user: fedoraAdmin
  fcrepo_password: fedoraAdmin
  fcrepo_basepath: /dev

  sidekiq_logfile: log/sidekiq_development.log

test:
  secret_key_base: 57caacef3de2f2367aee4d1ae099be5e149c0e821eaacf4c413798c931c82dc6e34a200f121316cb123b30ef3574a8acb82736a6bc76157132949233fd0340c5

  saml_assertion_consumer_service_url: ''
  saml_issuer: ''
  saml_private_key: ''
  saml_certificate: ''
  saml_idp_cert: ''
  saml_idp_sso_target_url: ''

  fcrepo_url: <%= ENV['FCREPO_URL'] || 'http://localhost:8080/fcrepo/rest' %>
  fcrepo_user: fedoraAdmin
  fcrepo_password: fedoraAdmin
  fcrepo_basepath: /test


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
uat:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  saml_assertion_consumer_service_url: 'localhost/auth/saml/callback'
  saml_issuer: 'https://era-test.library.ualberta.ca'
  saml_private_key: <%= ENV['SAML_PRIVATE_KEY'] %>
  saml_certificate: <%= ENV['SAML_CERTIFICATE'] %>
  saml_idp_cert: 'MIIEWzCCA0OgAwIBAgIJALoiStKRScIDMA0GCSqGSIb3DQEBCwUAMIHDMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHQWxiZXJ0YTERMA8GA1UEBwwIRWRtb250b24xHjAcBgNVBAoMFVVuaXZlcnNpdHkgb2YgQWxiZXJ0YTEqMCgGA1UECwwhSW5mb3JtYXRpb24gU2VydmljZXMgJiBUZWNobm9sb2d5MR4wHAYDVQQDDBVsb2dpbi11YXQudWFsYmVydGEuY2ExIzAhBgkqhkiG9w0BCQEWFHRhbnRvbmlvQHVhbGJlcnRhLmNhMB4XDTE2MDIwOTIyMzM0N1oXDTI2MDIwNjIyMzM0N1owgcMxCzAJBgNVBAYTAkNBMRAwDgYDVQQIDAdBbGJlcnRhMREwDwYDVQQHDAhFZG1vbnRvbjEeMBwGA1UECgwVVW5pdmVyc2l0eSBvZiBBbGJlcnRhMSowKAYDVQQLDCFJbmZvcm1hdGlvbiBTZXJ2aWNlcyAmIFRlY2hub2xvZ3kxHjAcBgNVBAMMFWxvZ2luLXVhdC51YWxiZXJ0YS5jYTEjMCEGCSqGSIb3DQEJARYUdGFudG9uaW9AdWFsYmVydGEuY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDdlCs9X2lvzaiC7WaQLsqQ4i'
  saml_idp_sso_target_url: 'https://login-uat.ualberta.ca/saml2/idp/SSOService.php'

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
  fcrepo_basepath: /uat

  sidekiq_logfile: log/sidekiq_uat.log

  
staging: *default
 
production: *default
