---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:queues:
 - critical
 - default
 - active_storage_analysis
 - active_storage_purge
 - mailers
 - low
development:
  :logfile: log/sidekiq_development.log
uat:
  :logfile: log/sidekiq_uat.log
production:
  :logfile: log/sidekiq_production.log
staging:
  :logfile: log/sidekiq_staging.log
