---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - default
  - mailers
development:
  :logfile: log/sidekiq_development.log
uat:
  :logfile: log/sidekiq_uat.log
production:
  :logfile: log/sidekiq_production.log
staging:
  :logfile: log/sidekiq_staging.log
