license:
  attribution_4_0_international: http://creativecommons.org/licenses/by/4.0/
  attribution_sharealike_4_0_international: http://creativecommons.org/licenses/by-sa/4.0/
  attribution_noncommercial_4_0_international: http://creativecommons.org/licenses/by-nc/4.0/
  attribution_noncommercial_noderivatives_4_0_international: http://creativecommons.org/licenses/by-nc-nd/4.0/
  cc0_1_0_universal: http://creativecommons.org/publicdomain/zero/1.0/
  attribution_noderivatives_4_0_international: http://creativecommons.org/licenses/by-nd/4.0/
  public_domain_mark_1_0: http://creativecommons.org/publicdomain/mark/1.0/
  attribution_noncommercial_sharealike_4_0_international: http://creativecommons.org/licenses/by-nc-sa/4.0/
